package org.infra.opti.multiTasking.automator;

import java.util.Date;

import org.infra.opti.multiTasking.models.Category;
import org.infra.opti.multiTasking.models.Product;

public class GeneratedProduct extends Product {	
	
	private int generatedProductId;
	private int requiredVersions;
	private Date generatedOn;
	
	public GeneratedProduct(Product base, int id){
		super(base.getProductId(), base.getName(), base.getDescription());
		setCategory(base.getCategory());
		setVersionInformation(base.getVersionInformation());
		generatedProductId = id;
		generatedOn = new Date();
	}

	public GeneratedProduct(int id, Category baseCategory, String threadName){
		super(id, threadName+ "_" + id, "Generated by thread " + threadName);
		setCategory(baseCategory);
		generatedProductId = id;
		generatedOn = new Date();
	}
	
	public int getGeneratedProductId() {
		return generatedProductId;
	}

	public void setGeneratedProductId(int generatedProductId) {
		this.generatedProductId = generatedProductId;
	}

	public Date getGeneratedOn() {
		return generatedOn;
	}

	public void setGeneratedOn(Date generatedOn) {
		this.generatedOn = generatedOn;
	}

	public int getRequiredVersions() {
		return requiredVersions;
	}

	public void setRequiredVersions(int requiredVersions) {
		this.requiredVersions = requiredVersions;
	}
	
	
}
